# Simple workflow for deploying static content to GitHub Pages
name: Deploy CGBC Web

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
    paths: [ cgbc.new/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: [ self-hosted ]
    name: Deploy CGBC Web
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Generate Build Number
        id: buildid
        uses: josStorer/get-current-time@v2.1.2
        with:
          utcOffset: "00:00"
          format: YYYY.MM.DD-HH.mm
      - name: List all changed files
        run: |
          Set-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Commit Item Messages:"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value $(git log --format=%B -n 1 HEAD)
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Build Number - ${{ steps.buildid.outputs.formattedTime }}"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value ""
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "Changed Files"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value "---------------------------------"
          Add-Content -Path C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt -Value $(git diff --name-status ORIG_HEAD..)
      - name: Create Backup
        run: |
          New-Item -ItemType "directory" -Path "C:/deployment-stage/cgbc/${{ steps.buildid.outputs.formattedTime }}/" -Force
          Copy-Item C:/www-root/cedargrovebaptist.church/* -Destination C:/deployment-stage/cgbc/${{ steps.buildid.outputs.formattedTime }}/ -Recurse
          Compress-Archive -Path "C:/deployment-stage/cgbc/${{ steps.buildid.outputs.formattedTime }}/*" -Update -DestinationPath C:/backups/cgbc-${{ steps.buildid.outputs.formattedTime }}.zip -CompressionLevel "Fastest"
          Remove-Item -Path C:/deployment-stage/cgbc/${{ steps.buildid.outputs.formattedTime }} -Recurse
      - name: Deploy New Code
        run: |
          cd cgbc.new/cgbcWeb
          dotnet build
          dotnet publish -c Release -o C:/www-root/cedargrovebaptist.church      
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          removeArtifacts: true
          tag: cgbc-${{ steps.buildid.outputs.formattedTime }}
          name: "Cedar Grove Baptist Church"
          bodyFile: C:/deployment-stage/cgbc-${{ steps.buildid.outputs.formattedTime }}.txt
          